/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TestHeader from "./TestHeader";
import TestStats from "./TestStats";
import TestAttempt from "./TestAttempt";
import TestSections from "./TestSections";
import TestResults from "./TestResults";
import TestAnswerKey from "./TestAnswerKey";

function TestComponent() {
  return (
    <main className="flex flex-col pt-8 pb-20 bg-white border-l border-gray-300 shadow-lg max-w-[600px]">
      <TestHeader />
      <TestStats />
      <TestAttempt />
      <hr className="mt-12 w-full bg-gray-300 border border-gray-300 border-solid min-h-[1px] max-md:mt-10 max-md:max-w-full" />
      <TestSections />
      <hr className="mt-8 w-full bg-gray-300 border border-gray-300 border-solid min-h-[1px] max-md:max-w-full" />
      <TestResults />
      <hr className="mt-10 w-full bg-gray-300 border border-gray-300 border-solid min-h-[1px] max-md:max-w-full" />
      <TestAnswerKey />
    </main>
  );
}

export default TestComponent;
