/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TestStats({ data }) {
 

  return (
    <section className="flex gap-5 mt-8 max-md:flex-wrap max-md:max-w-full">
      <div className="flex flex-col flex-1 justify-center items-start p-2.5 bg-gray-100 rounded-md max-md:pr-5">
        <div className="text-sm font-medium leading-4 text-gray-700 uppercase">
          Total Questions
        </div>
        <div className="mt-2.5 text-3xl font-semibold tracking-tight leading-9 text-black">
         
          <span className=""> {data.total_questions}</span>
        </div>
      </div>
      <div className="flex flex-col flex-1 justify-center items-start p-2.5 bg-gray-100 rounded-md max-md:pr-5">
        <div className="text-sm font-medium leading-4 text-gray-700 uppercase">
        Duration
        </div>
        <div className="mt-2.5 text-3xl font-semibold tracking-tight leading-9 text-black">
          
          <span className=""> {data.duration}</span>
        </div>
      </div>
      <div className="flex flex-col flex-1 justify-center items-start p-2.5 bg-gray-100 rounded-md max-md:pr-5">
        <div className="text-sm font-medium leading-4 text-gray-700 uppercase">
        Maximum Marks
        </div>
        <div className="mt-2.5 text-3xl font-semibold tracking-tight leading-9 text-black">
          
          <span className=""> {data.maximum_marks}</span>
        </div>
      </div>
    </section>
  );
}

export default TestStats;
