/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TestAttempt({data}) {
  return (
    <div className="flex gap-5 self-start mt-8 text-sm font-medium leading-6">
      <button className="flex gap-2 justify-center px-4 py-2 text-white bg-black rounded-md">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a1ff5793893a6309f7d2f08a80104818e8b3f52932d23998595d4aa2c29d22ed?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
          className="shrink-0 my-auto w-4 aspect-square"
          alt=""
        />
        <span>Attempt test</span>
      </button>
      <div className="flex-auto my-auto text-gray-700">
        <span className="text-xl font-bold leading-7 text-black">{data.attempts_remaining}</span> / {data.max_attempts}
        Attempts remaining
      </div>
    </div>
  );
}

export default TestAttempt;
