// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";

// function TestResults() {
//   const attempts = [
//     { number: 1, date: "12 Jan, 06:45 PM", marks: 136 },
//     { number: 2, date: "15 Jan, 11:30 PM", marks: 192 },
//     { number: 3, date: "20 Jan, 02:05 PM", marks: 238 },
//   ];

//   return (
//     <section className="flex flex-col px-6 mt-9 w-full text-black max-md:px-5 max-md:max-w-full">
//       <h2 className="flex gap-1.5 self-start text-lg font-semibold leading-7 whitespace-nowrap">
//         <img
//           loading="lazy"
//           src="https://cdn.builder.io/api/v1/image/assets/TEMP/d85da9b0517d46b74776652aa17c0d1b8f1c4dbb067c852d521824c42728391b?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
//           className="shrink-0 aspect-square w-[18px]"
//           alt=""
//         />
//         <span className="my-auto">Results</span>
//       </h2>
//       <div className="flex flex-col py-2.5 mt-4 text-base leading-6 rounded-md border border-gray-300 border-solid max-md:max-w-full">
//         <div className="flex gap-5 justify-between w-full text-sm font-medium leading-4 text-gray-500 max-md:flex-wrap max-md:pr-5 max-md:max-w-full">
//           <div className="py-1">Previous Attempt</div>
//           <div className="flex gap-1.5 py-1">
//             <div>Attempted On</div>
//             <img
//               loading="lazy"
//               src="https://cdn.builder.io/api/v1/image/assets/TEMP/c4f12ca78db34c50cea13c8e5e8ff1c448cd84d2a3149084444daead0a50d862?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
//               className="shrink-0 self-start w-3.5 aspect-[1.16]"
//               alt=""
//             />
//           </div>
//           <div className="flex gap-1.5 py-1">
//             <div>Marks obtained</div>
//             <img
//               loading="lazy"
//               src="https://cdn.builder.io/api/v1/image/assets/TEMP/c4f12ca78db34c50cea13c8e5e8ff1c448cd84d2a3149084444daead0a50d862?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
//               className="shrink-0 self-start w-3.5 aspect-[1.16]"
//               alt=""
//             />
//           </div>
//         </div>
//         {attempts.map((attempt, index) => (
//           <React.Fragment key={index}>
//             <hr className="shrink-0 mt-2.5 h-px bg-gray-300 border border-gray-300 border-solid max-md:max-w-full" />
//             <div className="flex gap-5 justify-between mt-2.5 w-full max-md:flex-wrap max-md:pr-5 max-md:max-w-full">
//               <div>Attempt {attempt.number}</div>
//               <div className="flex gap-5">
//                 <div className="flex-auto">{attempt.date}</div>
//                 <div className="my-auto">{attempt.marks}</div>
//                 <img
//                   loading="lazy"
//                   src="https://cdn.builder.io/api/v1/image/assets/TEMP/75902398ca4008ee3af9623ee84c58c268750a4e25a1624b4c3f9d21e742a9e6?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
//                   className="shrink-0 self-start w-4 aspect-square"
//                   alt=""
//                 />
//               </div>
//             </div>
//           </React.Fragment>
//         ))}
//       </div>
//     </section>
//   );
// }

// export default TestResults;
import React from "react";

function TestResults() {
  const attempts = [
    { number: 1, date: "12 Jan, 06:45 PM", marks: 136 },
    { number: 2, date: "15 Jan, 11:30 PM", marks: 192 },
    { number: 3, date: "20 Jan, 02:05 PM", marks: 238 },
  ];

  return (
    <section className="self-center mt-8 w-full max-w-[544px] max-md:max-w-full">
      <div className="overflow-x-auto">
        <table className="min-w-full table-auto border-collapse border border-gray-300">
          <thead>
            <tr>
              <th className="px-4 py-2 border border-gray-300 text-left">Attempt Number</th>
              <th className="px-4 py-2 border border-gray-300 text-left">Attempted On</th>
              <th className="px-4 py-2 border border-gray-300 text-left">Marks Obtained</th>
            </tr>
          </thead>
          <tbody>
            {attempts.map((attempt, index) => (
              <tr key={index} className="border border-gray-300">
                <td className="px-4 py-2 border border-gray-300">Attempt {attempt.number}</td>
                <td className="px-4 py-2 border border-gray-300">{attempt.date}</td>
                <td className="px-4 py-2 border border-gray-300">{attempt.marks}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export default TestResults;
