/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TestAnswerKey() {
  return (
    <section className="flex flex-col items-start  mt-9 w-full font-medium max-md:px-5 max-md:max-w-full">
      <h2 className="flex gap-1.5 text-lg font-semibold leading-7 text-black">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/90212d808b437940516353040aa12abbea5040d33e4b78dd9acc4f9e84f7fb93?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
          className="shrink-0  aspect-square w-[18px]"
          alt=""
        />
        <span className="flex-auto">Answer Key</span>
      </h2>
      <p className="self-stretch mt-3.5 text-xs leading-5 text-gray-500 max-md:max-w-full">
        Answer key is available to view after the first attempt. Its up to you
        how you wish to use this.
        <br />
        In case you want to have more attempts, we recommend not to look at the
        answer key until you have exhausted all your attempts
      </p>
      <button className="flex gap-2 justify-center px-4 py-2 mt-6 text-sm leading-6 text-white bg-black rounded-md">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0f7b586ef954a50e394c201a9a57a7958cc1688b2b1b41b2d15cac69d96f0df4?apiKey=8a82faa9db93454483a68c973b38c7b0&&apiKey=8a82faa9db93454483a68c973b38c7b0"
          className="shrink-0 my-auto w-4 aspect-square"
          alt=""
        />
        <span>View answers -&gt;</span>
      </button>
    </section>
  );
}

export default TestAnswerKey;
