/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TestStats() {
  const stats = [
    { label: "Total Questions", value: "90" },
    { label: "Duration", value: "120", unit: "minutes" },
    { label: "Maximum Marks", value: "250" },
  ];

  return (
    <section className="flex gap-5 mt-8 max-md:flex-wrap max-md:max-w-full">
      {stats.map((stat, index) => (
        <div
          key={index}
          className="flex flex-col flex-1 justify-center items-start p-2.5 bg-gray-100 rounded-md max-md:pr-5"
        >
          <div className="text-sm font-medium leading-4 text-gray-700 uppercase">
            {stat.label}
          </div>
          <div className="mt-2.5 text-3xl font-semibold tracking-tight leading-9 text-black">
            {stat.value}
            {stat.unit && (
              <span className="text-base leading-7"> {stat.unit}</span>
            )}
          </div>
        </div>
      ))}
    </section>
  );
}

export default TestStats;
