/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SubmitButton = () => {
  return (
    <button
      type="submit"
      className="justify-center self-start px-4 py-2 mt-5 text-sm font-medium leading-6 text-white whitespace-nowrap rounded-md bg-slate-900"
    >
      Submit
    </button>
  );
};

export default SubmitButton;
